name: CI/CD - back

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:back"
          push: true
          tags: |
            tarikly/andela-back:latest
            tarikly/andela-back:${{ github.sha }}

  deploy:
    name: Deploy
    needs: [ docker ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://ec2-100-26-175-135.compute-1.amazonaws.com:6443/
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}


      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: Azure/k8s-deploy@v5
        with:
          skip-tls-verify: true
          namespace: 'andela'
          manifests: |
              back/kubernetes/deployment.yaml
          images: 'tarikly/andela-back:${{ github.sha }}'
          imagepullsecrets: |
              github-container-registry
