name: front - docker docs - auto

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "front"
          push: false
          tags: |
            tarikly/andela-front:latest
            tarikly/andela-front:${{ github.sha }}

  deploy:
    name: Deploy
    needs: [ docker ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_API_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: Azure/k8s-deploy@v5
        with:
          skip-tls-verify: true
          namespace: 'andela'
          manifests: |
              front/kubernetes/deployment.yaml
          images: 'tarikly/andela-front:${{ github.sha }}'